name       : lf
version    : 19
release    : 5
source     :
    - https://github.com/gokcehan/lf/archive/r19.tar.gz : 8808069021ee1c0012440edabdc239b9f58f36bdd44d27b07eae7c91b97afdef
homepage   : https://github.com/gokcehan/lf
license    : MIT
component  : system.utils
summary    : A terminal file manager written in go
description: |
    lf (as in "list files") is a terminal file manager written in Go. It is heavily inspired by ranger with some missing and extra features. Some of the missing features are deliberately omitted since they are better handled by external tools.
networking : yes
builddeps  :
    - golang
build      : |
    go build -ldflags "-s -w" -o lf
install    : |
    install -Dm00755 lf $installdir/usr/bin/lf
    install -Dm00644 lf.1 $installdir/usr/share/man/man1/lf.1
    install -Dm00644 lf.desktop $installdir/usr/share/applications/lf.desktop
    install -Dm00644 etc/lfrc.example $installdir/usr/share/doc/lf/examples/lfrc

    install -Dm00644 etc/lf.bash installdir/usr/share/bash-completion/completions/lf
    install -Dm00644 etc/lf.fish $installdir/usr/share/fish/vendor_completions.d/lf.fish
    install -Dm00644 etc/lf.zsh $installdir/usr/share/zsh/site-functions/_lf

    install -Dm00644 etc/lfcd.sh $installdir/usr/share/defaults/etc/profile.d/lfcd.sh
    install -Dm00644 etc/lfcd.fish $installdir/usr/share/fish/vendor_functions.d/lfcd.fish
    install -Dm00644 etc/lfcd.sh $installdir/usr/share/zsh/site-functions/lfcd.sh

    install -Dm00644 etc/lf.vim $installdir/usr/share/vim/vimfiles/plugin/lf.vim
